domain_path: /home/hyeonjun/AMD/Vivado/source/camera2hdmi_final1.01/camera2hdmi_final1.01/vitis_workspace/my_platform/export/my_platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /tools/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
